blank_issues_enabled: false
contact_links:
  - name: Security vulnerability disclosure
    url: https://github.com/novaeco/n32r16/security/policy
    about: Please report potential vulnerabilities privately.
