#pragma once

#include "driver/gpio.h"

#define LCD_DE_GPIO GPIO_NUM_5
#define LCD_VSYNC_GPIO GPIO_NUM_3
#define LCD_HSYNC_GPIO GPIO_NUM_46
#define LCD_PCLK_GPIO GPIO_NUM_7
#define LCD_DATA0_GPIO GPIO_NUM_42
#define LCD_DATA1_GPIO GPIO_NUM_41
#define LCD_DATA2_GPIO GPIO_NUM_40
#define LCD_DATA3_GPIO GPIO_NUM_39
#define LCD_DATA4_GPIO GPIO_NUM_45
#define LCD_DATA5_GPIO GPIO_NUM_48
#define LCD_DATA6_GPIO GPIO_NUM_47
#define LCD_DATA7_GPIO GPIO_NUM_21
#define LCD_DATA8_GPIO GPIO_NUM_14
#define LCD_DATA9_GPIO GPIO_NUM_38
#define LCD_DATA10_GPIO GPIO_NUM_18
#define LCD_DATA11_GPIO GPIO_NUM_17
#define LCD_DATA12_GPIO GPIO_NUM_10
#define LCD_DATA13_GPIO GPIO_NUM_12
#define LCD_DATA14_GPIO GPIO_NUM_11
#define LCD_DATA15_GPIO GPIO_NUM_13

#define TOUCH_SCL_GPIO GPIO_NUM_9
#define TOUCH_SDA_GPIO GPIO_NUM_8
#define TOUCH_INT_GPIO GPIO_NUM_4
#define TOUCH_RST_GPIO GPIO_NUM_2

