name: ESP-IDF Build & Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      IDF_VERSION: v5.5
      IDF_PATH: ${{ github.workspace }}/esp-idf
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache ESP-IDF
        uses: actions/cache@v4
        with:
          path: ${{ env.IDF_PATH }}
          key: esp-idf-${{ env.IDF_VERSION }}

      - name: Install ESP-IDF
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          git clone --depth 1 --branch ${IDF_VERSION} https://github.com/espressif/esp-idf.git ${IDF_PATH}
          ${IDF_PATH}/install.sh esp32s3

      - name: Export ESP-IDF
        run: |
          . ${IDF_PATH}/export.sh
          python --version

      - name: Build sensor node
        run: |
          . ${IDF_PATH}/export.sh
          cd sensor_node
          idf.py set-target esp32s3
          idf.py build
          idf.py -T tests

      - name: Build HMI node
        run: |
          . ${IDF_PATH}/export.sh
          cd hmi_node
          idf.py set-target esp32s3
          idf.py build
          idf.py -T tests

